import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {StudioAnalytics,parseCSV,parseReachCSV,aggregateReach} from '../studio-analytics.mjs';
import {ContentStore} from '../content-store.mjs';
import {AnalyticsStore} from '../analytics-store.mjs';
import {YouTubeManager} from '../youtube-manager.mjs';
import {analyticsRange} from '../analytics.mjs';
const channel='UC-test',a='abcdefghijk',b='lmnopqrstuv',range={startDate:'2026-09-29',endDate:'2026-09-30',days:2};
const metadata=id=>({id,etag:'etag-1',snippet:{channelId:channel,title:'Judul '+id,description:'Deskripsi tetap',categoryId:'22',tags:['awal'],defaultLanguage:'id',thumbnails:{medium:{url:'https://i.ytimg.com/vi/'+id+'/mqdefault.jpg'}}},contentDetails:{duration:'PT5M'},statistics:{viewCount:'999'},status:{privacyStatus:'public'}});
const analyticsReport=params=>{const dims=(params.get('dimensions')||'').split(',').filter(Boolean),metrics=params.get('metrics').split(','),values={views:100,estimatedMinutesWatched:200,averageViewDuration:120,averageViewPercentage:50,subscribersGained:5,subscribersLost:2,likes:12,comments:8,shares:2,engagedViews:95,viewerPercentage:100,estimatedRevenue:3.2,estimatedAdRevenue:3,estimatedRedPartnerRevenue:.2,monetizedPlaybacks:40,playbackBasedCpm:4,adImpressions:45,audienceWatchRatio:.6,relativeRetentionPerformance:.5};const dimension={video:a,day:params.get('endDate'),ageGroup:'age25-34',gender:'male',creatorContentType:'VIDEO_ON_DEMAND',elapsedVideoTimeRatio:.5,insightTrafficSourceType:'YT_SEARCH',insightTrafficSourceDetail:'kata kunci',deviceType:'MOBILE',country:'ID',subscribedStatus:'UNSUBSCRIBED'};return {columnHeaders:[...dims.map(name=>({name,columnType:'DIMENSION'})),...metrics.map(name=>({name,columnType:'METRIC'}))],rows:[[...dims.map(name=>dimension[name]),...metrics.map(name=>values[name]||0)]]}};
async function setup(fn){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'yt-studio-'));try{await fn(path.join(dir,'analytics.json'))}finally{await fs.rm(dir,{recursive:true,force:true})}}
test('persistent Analytics writes serialize, isolate channels, survive restart, and preserve corrupt data',()=>setup(async file=>{const s=new AnalyticsStore(file);await Promise.all(Array.from({length:15},(_,i)=>s.mutate('A',c=>{c.videos['v'+i]={title:'Judul '+i}})));assert.equal(Object.keys((await new AnalyticsStore(file).read('A')).videos).length,15);assert.equal(Object.keys((await s.read('B')).videos).length,0);await s.remove('A');assert.deepEqual((await s.read('A')).videos,{});await fs.writeFile(file,'bad-json');await assert.rejects(new AnalyticsStore(file).read('A'),e=>e.code==='storage_error');assert.equal(await fs.readFile(file,'utf8'),'bad-json')}));
test('Reach CSV accepts quoted columns and weights percentage CTR; partial days and no impressions remain explicit',()=>{assert.equal(parseCSV('a,b\r\n"x,y","z""q"\r\n').rows[0].a,'x,y');assert.throws(()=>parseCSV('a,b\n"broken'));const report={id:'report-1',startTime:'2026-09-29T08:00:00Z',createTime:'2026-10-01T10:00:00Z'};const csv=`date,channel_id,video_id,video_thumbnail_impressions,video_thumbnail_impressions_ctr\n2026-09-29,${channel},${a},100,10\n2026-09-29,${channel},${b},900,2\n`;const day=parseReachCSV(csv,channel,report);const out=aggregateReach({'2026-09-29':day},range);assert.equal(out.impressions,1000);assert.equal(out.ctr,2.8);assert.equal(out.complete,false);assert.equal(out.coveredDays,1);assert.equal(aggregateReach({'2026-09-29':day},range,a).ctr,10);assert.equal(aggregateReach({},range).impressions,null);assert.throws(()=>parseReachCSV(csv,'other',report));assert.throws(()=>parseReachCSV(csv.replace(',900,2',',-1,2'),channel,report));assert.throws(()=>parseReachCSV(csv.replace(',100,10',',100,101'),channel,report));});
test('cached titles survive quota errors and restarts; incomplete batches are retained and metadata scopes cannot leak',()=>setup(async file=>{let quota=false,now=Date.now(),calls=0;const fetcher=async url=>{calls++;if(quota)return Response.json({error:{errors:[{reason:'quotaExceeded'}]}},{status:403});const ids=new URL(url).searchParams.get('id').split(',');return Response.json({items:ids.map(metadata)})};const api=new StudioAnalytics(fetcher,{file,now:()=>now});assert.equal((await api.metadata(channel,[a])).items[0].snippet.title,'Judul '+a);assert.equal(calls,1);await api.metadata(channel,[a]);assert.equal(calls,1);now+=2*86400000;quota=true;const restarted=new StudioAnalytics(fetcher,{file,now:()=>now}),m=await restarted.metadata(channel,[a]);assert.equal(m.items[0].snippet.title,'Judul '+a);assert.equal(m.warnings[0].code,'quota_exceeded');await restarted.metadata(channel,[a]);assert.equal(calls,2);const wrong=new StudioAnalytics(async()=>Response.json({items:[{...metadata(a),snippet:{...metadata(a).snippet,channelId:'other'}}]}),{file:file+'.wrong'});await assert.rejects(wrong.metadata(channel,[a]),e=>e.code==='wrong_channel')}));
test('public title fallback does not receive OAuth headers and uses a fixed YouTube URL',()=>setup(async file=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=async(url,options)=>{assert.equal(new URL(url).hostname,'www.youtube.com');assert.equal(options.headers,undefined);calls++;return Response.json({title:'Nama publik dari YouTube'})};try{const api=new StudioAnalytics(async()=>Response.json({error:{errors:[{reason:'quotaExceeded'}]}},{status:403}),{file});const m=await api.metadata(channel,[a],{publicFallback:true});assert.equal(m.items[0].snippet.title,'Nama publik dari YouTube');assert.equal(m.items[0].metadataSource,'oembed');await api.metadata(channel,[a]);assert.equal(calls,1)}finally{globalThis.fetch=original}}));
test('catalog paginates uploads and retains videos without period rows as unavailable instead of zero',()=>setup(async file=>{const urls=[];const api=new StudioAnalytics(async url=>{const u=new URL(url);urls.push(u);if(u.hostname.includes('youtubeanalytics'))return Response.json(analyticsReport(u.searchParams));if(u.pathname.endsWith('/channels'))return Response.json({items:[{id:channel,snippet:{title:'Test'},contentDetails:{relatedPlaylists:{uploads:'UUtest'}},statistics:{viewCount:'100'}}]});if(u.pathname.endsWith('/playlistItems'))return Response.json({items:[{snippet:{title:'Video '+(u.searchParams.has('pageToken')?b:a),resourceId:{videoId:u.searchParams.has('pageToken')?b:a}}}],...(u.searchParams.has('pageToken')?{}:{nextPageToken:'page-two'})});return Response.json({items:u.searchParams.get('id').split(',').map(metadata)})},{file});const status=await api.syncCatalog(channel);assert.equal(status.status,'ready');assert.equal(status.count,2);assert.equal(urls.filter(u=>u.pathname.endsWith('/playlistItems')).length,2);const list=await api.listVideos(channel,analyticsRange(new URLSearchParams('days=7')));assert.equal(list.catalogCount,2);assert.equal(list.videos.find(v=>v.id===b).hasPeriodData,false);assert.equal(list.videos.find(v=>v.id===b).views,undefined);assert.equal(list.videos.find(v=>v.id===a).views,100);assert.equal((await api.get(channel,analyticsRange(new URLSearchParams('days=7')))).topVideos[0].title,'Judul '+a)}));
test('Reach jobs import once and backfill replaces the same day; malformed downloads cannot replace good metrics',()=>setup(async file=>{let revision=1,downloads=0,invalid=false;const day='2026-09-29';const api=new StudioAnalytics(async(url,options)=>{const u=new URL(url);if(u.pathname.endsWith('/reportTypes'))return Response.json({reportTypes:[{id:'channel_reach_basic_a1'}]});if(u.pathname==='/v1/jobs')return Response.json(options?.method==='POST'?{id:'job-1'}:{jobs:[]});if(u.pathname.endsWith('/reports'))return Response.json({reports:[{id:'report-'+revision,startTime:day+'T08:00:00Z',createTime:`2026-10-01T10:00:0${revision}Z`,downloadUrl:'https://youtubereporting.googleapis.com/v1/media/report-'+revision}]});downloads++;return new Response(`date,channel_id,video_id,video_thumbnail_impressions,video_thumbnail_impressions_ctr\n${day},${invalid?'wrong':channel},${a},${revision*100},4\n`)},{file});assert.equal((await api.syncReach(channel)).status,'ready');await api.syncReach(channel);assert.equal(downloads,1);revision=2;await api.syncReach(channel);assert.equal((await api.store.read(channel)).reach[day].byVideo[a].impressions,200);revision=3;invalid=true;assert.equal((await api.syncReach(channel)).status,'error');assert.equal((await api.store.read(channel)).reach[day].byVideo[a].impressions,200);assert.equal(aggregateReach((await api.store.read(channel)).reach,range).impressions,200)}));
test('advanced channel and video reports isolate filters, expose audience and gate monetary consent',()=>setup(async file=>{let monetary=false;const urls=[];const api=new StudioAnalytics(async url=>{const u=new URL(url);urls.push(u);return Response.json(u.hostname.includes('youtubeanalytics')?analyticsReport(u.searchParams):{items:[metadata(a)]})},{file,monetary:async()=>monetary});const r=analyticsRange(new URLSearchParams('days=7'));const channelReport=await api.get(channel,r);assert.equal(channelReport.engagedViews,95);assert.equal(channelReport.demographics[0].age,'age25-34');assert.equal(channelReport.revenue.status,'authorization_required');assert.ok(!urls.some(u=>u.searchParams.get('metrics')?.includes('estimatedRevenue')));monetary=true;api.clear();const detail=await api.getVideo(channel,a,r);assert.equal(detail.revenue.summary.estimatedRevenue,3.2);assert.equal(detail.revenue.currency,'USD');assert.ok(urls.filter(u=>u.searchParams.get('metrics')?.includes('estimatedRevenue')).every(u=>u.searchParams.get('filters')==='video=='+a));assert.equal(detail.video.title,'Judul '+a);assert.ok(detail.retention.length)}));
test('disconnect blocks in-flight metadata persistence and cached reports',()=>setup(async file=>{let release;const wait=new Promise(r=>release=r);const api=new StudioAnalytics(async()=>{await wait;return Response.json({items:[metadata(a)]})},{file});const work=api.metadata(channel,[a]);await new Promise(r=>setImmediate(r));api.clear();release();await assert.rejects(work,e=>e.code==='channel_changed');assert.deepEqual((await api.store.read(channel)).videos,{})}));
test('video management validates before writing, preserves snippet fields, checks etags, and verifies ownership',async()=>{let writes=0,body=null,etag='etag-1';const manager=new YouTubeManager(async(url,options)=>{if(options.method==='PUT'){writes++;body=JSON.parse(options.body);assert.equal(options.headers['if-match'],etag);return Response.json({id:a})}return Response.json({items:[{...metadata(a),etag}]})});await assert.rejects(manager.save(channel,a,{title:' ',description:'',tags:[]}),e=>e.status===400);assert.equal(writes,0);await assert.rejects(manager.save(channel,a,{title:'New',description:'',tags:[],etag:'old'}),e=>e.status===409);assert.equal(writes,0);await manager.save(channel,a,{title:'New',description:'Isi',tags:['x'],etag});assert.equal(writes,1);assert.equal(body.snippet.categoryId,'22');assert.equal(body.snippet.defaultLanguage,'id');await assert.rejects(manager.details('other',a),e=>e.status===404);await assert.rejects(manager.thumbnail(channel,a,{base64:Buffer.from('not image').toString('base64')}),e=>e.status===400)});
test('comment replies and playlist additions reject cross-video and cross-channel targets',async()=>{let writes=0;const manager=new YouTubeManager(async(url,options)=>{if(options.method==='POST'){writes++;return Response.json({})}const u=new URL(url);if(u.pathname.endsWith('/videos'))return Response.json({items:[metadata(a)]});if(u.pathname.endsWith('/comments'))return Response.json({items:[{id:'comment-1',snippet:{videoId:b}}]});if(u.pathname.endsWith('/playlists'))return Response.json({items:[{id:'PL-test',snippet:{channelId:'other'}}]});return Response.json({items:[]})});await assert.rejects(manager.reply(channel,a,{parentId:'comment-1',text:'Balasan'}),e=>e.status===404);await assert.rejects(manager.addPlaylist(channel,a,{playlistId:'PL-test'}),e=>e.status===404);assert.equal(writes,0)});

test('video production links are unique under concurrent creation, survive restoration, and clear on duplication',()=>setup(async file=>{const store=new ContentStore(file+'.contents'),base=await store.create({title:'Naskah awal'});const linked=await store.update(base.id,{revision:base.revision,youtubeVideoId:a});const restored=await store.update(base.id,{revision:linked.revision,restoreRevision:base.revision});assert.equal(restored.youtubeVideoId,a);assert.equal((await store.duplicate(base.id)).youtubeVideoId,'');const results=await Promise.allSettled([store.create({title:'Video B',youtubeVideoId:b}),store.create({title:'Video B ulang',youtubeVideoId:b})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await store.read()).contents.filter(c=>c.youtubeVideoId===b).length,1)}));
test('Reach preserves impressions for unassigned/deleted video rows in channel totals',()=>{const report={id:'deleted',startTime:'2026-09-29T08:00:00Z',createTime:'2026-10-01T10:00:00Z'},csv=`date,channel_id,video_id,video_thumbnail_impressions,video_thumbnail_impressions_ctr\n2026-09-29,${channel},${a},100,10\n2026-09-29,${channel},,900,2\n`,parsed=parseReachCSV(csv,channel,report);assert.equal(aggregateReach({'2026-09-29':parsed},range).ctr,2.8);assert.equal(aggregateReach({'2026-09-29':parsed},range,a).impressions,100)});
test('manual sync can recover immediately after API activation while scheduled retries obey backoff',()=>setup(async file=>{let disabled=true,calls=0;const api=new StudioAnalytics(async url=>{calls++;if(disabled)return Response.json({error:{errors:[{reason:'accessNotConfigured'}]}},{status:403});const u=new URL(url);if(u.pathname==='/v1/reportTypes')return Response.json({reportTypes:[{id:'channel_reach_basic_a1'}]});if(u.pathname==='/v1/jobs')return Response.json({id:'job',jobs:[]});return Response.json({reports:[]})},{file});assert.equal((await api.syncReach(channel)).status,'error');const count=calls;disabled=false;await api.syncReach(channel);assert.equal(calls,count);assert.equal((await api.syncReach(channel,{force:true})).status,'waiting');assert.ok(calls>count)}));
