import http from 'node:http';
import https from 'node:https';
import dns from 'node:dns/promises';
import net from 'node:net';
import { parseDocument, DomUtils } from 'htmlparser2';
import { fail, canonicalUrl, matchesTopic, radarData } from './radar-store.mjs';
export function publicAddress(ip){if(net.isIPv4(ip)){const [a,b]=ip.split('.').map(Number);return !(a===0||a===10||a===127||a>=224||a===169&&b===254||a===172&&b>=16&&b<=31||a===192&&(b===168||b===0)||a===100&&b>=64&&b<=127||a===198&&(b===18||b===19||b===51)||a===203&&b===0);}if(net.isIPv6(ip))return /^2[0-9a-f]{3}:/i.test(ip)&&!/^2001:(db8|0|2):/i.test(ip);return false;}
export async function safeFeed(url,redirects=0){const u=new URL(canonicalUrl(url));if(u.port&&!['80','443'].includes(u.port))throw fail('Port RSS harus 80/443.');const host=u.hostname.replace(/^\[|\]$/g,''),addresses=net.isIP(host)?[{address:host,family:net.isIP(host)}]:await dns.lookup(host,{all:true});if(!addresses.length||addresses.some(x=>!publicAddress(x.address)))throw fail('Alamat RSS harus server publik.');return new Promise((resolve,reject)=>{const request=(u.protocol==='https:'?https:http).get(u,{headers:{'user-agent':'ContentHub-Radar/4.7','accept':'application/rss+xml, application/atom+xml, application/xml, text/xml'},lookup:(h,opts,cb)=>opts.all?cb(null,[addresses[0]]):cb(null,addresses[0].address,addresses[0].family)},response=>{if([301,302,303,307,308].includes(response.statusCode)){response.resume();if(redirects>=3)return reject(fail('Terlalu banyak redirect RSS.'));try{safeFeed(new URL(response.headers.location,u).href,redirects+1).then(resolve,reject)}catch(e){reject(e)}return;}if(response.statusCode!==200){response.resume();return reject(fail('RSS mengembalikan HTTP '+response.statusCode));}let size=0,parts=[];response.on('data',part=>{size+=part.length;if(size>512*1024){request.destroy(fail('RSS melebihi 512 KB.'));return;}parts.push(part)});response.on('end',()=>resolve(Buffer.concat(parts).toString('utf8')));response.on('error',reject);});const deadline=setTimeout(()=>request.destroy(fail('RSS melewati batas waktu.')),20000);request.on('close',()=>clearTimeout(deadline));request.setTimeout(12000,()=>request.destroy(fail('RSS terlalu lama merespons.')));request.on('error',reject);});}
export function parseFeed(xml,publisher='RSS'){const root=parseDocument(xml,{xmlMode:true,decodeEntities:true}),nodes=DomUtils.findAll(n=>['item','entry'].includes(n.name),root.children).slice(0,30);return nodes.flatMap(n=>{const child=name=>n.children?.find(x=>x.name===name),val=name=>DomUtils.textContent(child(name)||{children:[]}).trim();const link=val('link')||child('link')?.attribs?.href,title=val('title');if(!link||!title)return [];let url;try{url=canonicalUrl(link)}catch{return [];}const pub=val('pubDate')||val('published'),excerpt=(val('content:encoded')||val('content')||val('description')||val('summary')).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').slice(0,3000);return [{url,title:title.slice(0,300),publisher:(val('source')||publisher).slice(0,160),...(child('source')?.attribs?.url?(()=>{try{return {publisherUrl:canonicalUrl(child('source').attribs.url)}}catch{return {}}})():{}),publishedAt:Number.isFinite(Date.parse(pub))?new Date(pub).toISOString():null,excerpt,coverage:excerpt?'snippet':'headline'}];});}
export function freshNews(sources,now=Date.now()){
 return sources.filter(source=>{const age=now-Date.parse(source.publishedAt||'');return Number.isFinite(age)&&age>=0&&age<168*3600000;});
}
export class RadarSync{
 constructor(store,youtube,{feed=safeFeed,now=()=>Date.now()}={}){this.store=store;this.youtube=youtube;this.feed=feed;this.now=now;this.busy=false;}
 async sync({force=false}={}){if(this.busy)throw fail('Sinkronisasi Radar sedang berjalan.',409);this.busy=true;const result={news:0,videos:0,errors:[]};try{await this.store.recluster();const r=radarData(await this.store.contentStore.read()),at=this.now();if(!force&&at-Date.parse(r.sync.lastAttemptAt||0)<3600000)return {skipped:true};if(force&&at-Date.parse(r.sync.lastAttemptAt||0)<60000)throw fail('Tunggu satu menit sebelum sinkronisasi berikutnya.',429);await this.store.mutate(r=>{r.sync.lastAttemptAt=new Date(at).toISOString()});const topics=r.topics.filter(t=>t.enabled&&t.sources.includes('news')),offset=(r.sync.cursor||0)%Math.max(1,topics.length),selected=Array.from({length:Math.min(3,topics.length)},(_,i)=>topics[(offset+i)%topics.length]);let succeeded=false;const keywordOffsets={...(r.sync.keywordOffsets||{})};for(const t of selected){try{const keywordOffset=(keywordOffsets[t.id]||0)%t.keywords.length,keywords=Array.from({length:Math.min(6,t.keywords.length)},(_,i)=>t.keywords[(keywordOffset+i)%t.keywords.length]);keywordOffsets[t.id]=keywordOffset+keywords.length;const q=keywords.map(k=>'"'+k.replace(/["()]/g,'')+'"').join(' OR '),url='https://news.google.com/rss/search?'+new URLSearchParams({q,hl:t.language,gl:t.region,ceid:t.region+':'+t.language});const sources=freshNews(parseFeed(await this.feed(url),'Google News'),at).filter(s=>matchesTopic(s,t));if(sources.length)await this.store.addSources(sources,[t.id]);result.news+=sources.length;succeeded=true;}catch(e){result.errors.push({source:t.name,message:e.message.slice(0,300)})}}for(const f of r.feeds.filter(x=>x.enabled)){try{const sources=freshNews(parseFeed(await this.feed(f.url),f.name),at).filter(s=>r.topics.some(t=>t.sources.includes('news')&&matchesTopic(s,t)));if(sources.length)await this.store.addSources(sources);result.news+=sources.length;succeeded=true;}catch(e){result.errors.push({source:f.name,message:e.message.slice(0,300)})}}for(const c of r.channels.filter(c=>c.enabled)){if(Date.parse(r.sync.youtubeRetryAt)>this.now()){result.errors.push({source:'YouTube',message:'Kuota YouTube sedang dibatasi sampai '+r.sync.youtubeRetryAt});break;}try{result.videos+=await this.channel(c,r.topics);}catch(e){result.errors.push({source:c.name||c.url,message:e.message.slice(0,300)});if(e.code==='quota_exceeded'){await this.store.mutate(r=>{r.sync.youtubeRetryAt=new Date(this.now()+3600000).toISOString()});break;}}}await this.store.mutate(r=>{r.sync={...r.sync,cursor:offset+selected.length,keywordOffsets,lastCompletedAt:new Date(this.now()).toISOString(),errors:result.errors,...(succeeded?{newsAt:new Date(this.now()).toISOString()}:{})};});await this.store.observe();return result;}finally{this.busy=false}}
 async yt(resource,params){const response=await this.youtube('https://www.googleapis.com/youtube/v3/'+resource+'?'+new URLSearchParams(params));const data=await response.json();if(!response.ok){const quota=data.error?.errors?.some(x=>['quotaExceeded','dailyLimitExceeded'].includes(x.reason));throw Object.assign(fail(quota?'Kuota YouTube habis. Data sebelumnya tetap tersedia.':data.error?.message||'YouTube belum terhubung.',503),{code:quota?'quota_exceeded':'youtube_error'});}return data.items||[];}
 async channel(c,topics){let channelId=c.channelId,uploads=c.uploads,name=c.name,thumbnail=c.thumbnail;if(!channelId||!uploads){const u=new URL(c.url),handle=u.pathname.startsWith('/@');const [channel]=await this.yt('channels',{part:'snippet,contentDetails',...(handle?{forHandle:decodeURIComponent(u.pathname.slice(1))}:{id:u.pathname.split('/')[2]})});if(!channel)throw fail('Channel tidak ditemukan.',404);channelId=channel.id;uploads=channel.contentDetails.relatedPlaylists.uploads;name=channel.snippet.title;thumbnail=channel.snippet.thumbnails?.default?.url||'';}const entries=await this.yt('playlistItems',{part:'contentDetails',playlistId:uploads,maxResults:'10'}),ids=entries.map(x=>x.contentDetails.videoId);const videos=ids.length?await this.yt('videos',{part:'snippet,contentDetails,statistics',id:ids.join(',')}):[];const now=new Date(this.now()).toISOString(),snapshot={at:now,values:{}};const mapped=videos.map(v=>{const previous=c.snapshots?.at(-1),old=previous?.values?.[v.id];const stats=Object.fromEntries(['viewCount','likeCount','commentCount'].map(k=>[k,v.statistics?.[k]===undefined?null:Number(v.statistics[k])]));snapshot.values[v.id]=stats;return {id:v.id,title:v.snippet.title,url:'https://www.youtube.com/watch?v='+v.id,thumbnail:v.snippet.thumbnails?.medium?.url||'',publishedAt:v.snippet.publishedAt,duration:v.contentDetails.duration,...stats,delta:old?Object.fromEntries(Object.keys(stats).map(k=>[k,stats[k]===null||old[k]===null||old[k]===undefined?null:stats[k]-old[k]])):null,previousAt:old?previous.at:null};});const persisted=await this.store.mutate(r=>{const current=r.channels.find(x=>x.id===c.id);if(!current)return false;Object.assign(current,{channelId,uploads,name,thumbnail,videos:mapped,lastSyncAt:now});current.snapshots=[...(current.snapshots||[]),snapshot].slice(-30);return true;});if(!persisted)return 0;for(const v of mapped){const source={...v,publisher:name,coverage:'headline'},matches=topics.filter(t=>t.sources.includes('youtube')&&matchesTopic(source,t)).map(t=>t.id);if(matches.length)await this.store.addSources([source],matches);}return mapped.length;}
}
