export const APP_VERSION='4.10.0';
// Release dates follow WIB. This is the shipped application history, not user edits.
export const RELEASES=[
 {version:'4.10.0',date:'2026-10-03',title:'Radar Hot News, kelompok judul dan rating',changes:[{type:'feature',text:'Berita dengan judul serupa dikelompokkan berdasarkan kata penting, variasi kata, dan kedekatan waktu. Perbedaan lokasi, tahun, angka kebijakan, dan keputusan tertentu mencegah penggabungan yang keliru.'},{type:'feature',text:'Hot News menampilkan isu dengan rating minimal 4/5, skor 65/100, tiga penerbit berbeda dalam 72 jam dan dua aktif dalam 24 jam, serta berita terbaru yang sesuai topik aktif.'},{type:'fix',text:'Kebaruan memakai tanggal publikasi. Repost, satu penerbit dengan banyak link, berita lama yang baru diimpor, dan berita tanpa tanggal tidak membuat isu menjadi hot.'},{type:'feature',text:'Rating bintang, komponen skor, judul asli dan link sumber tampil di detail. Referensi tersimpan tetap bisa dibuka; bahan lain dikelola melalui Topik & Sumber.'},{type:'fix',text:'Impor mesin lama yang belum disunting dikelompokkan ulang setelah backup. Judul editorial, verifikasi, referensi, dan hubungan konten dijaga. Sinkronisasi berita berjalan sekitar setiap satu jam.'}]},
 {version:'4.9.1',date:'2026-10-02',title:'Waktu AI mengikuti provider yang aktif',changes:[{type:'fix',text:'Satu provider aktif mendapat seluruh batas waktu 60 detik. Jika ada cadangan, waktu tersisa dibagi agar perpindahan tetap dapat dilakukan.'},{type:'fix',text:'Gemini 3 Flash/Pro memakai tingkat penalaran low untuk bantuan editor dan uji jawaban. Uji jawaban serta script sintetis memakai deadline 60 detik.'}]},
 {version:'4.9.0',date:'2026-10-02',title:'Metode AI teks biasa dan uji jawaban nyata',changes:[{type:'fix',text:'Script, ringkasan, storyboard, dan analisis memakai keluaran teks biasa tanpa persyaratan JSON terstruktur provider. Tiga Short tetap divalidasi sebelum dibuka sebagai draft.'},{type:'feature',text:'Uji jawaban mengirim bahan sintetis singkat untuk membedakan katalog API terhubung dan model yang benar-benar dapat menghasilkan teks. Rincian tiap provider tampil tanpa API key.'},{type:'fix',text:'Cadangan dicoba saat kuota habis, gangguan layanan, timeout, key ditolak atau model tidak ditemukan. Setiap provider dicoba sekali, maksimal 20 detik; penolakan konten serta rujukan tidak valid tetap menghentikan rangkaian.'},{type:'fix',text:'Hanya pratinjau yang berhasil dihitung ke batas harian aplikasi. Reservasi gagal dikembalikan; reservasi yang tertinggal dipulihkan setelah kedaluwarsa.'}]},
 {version:'4.8.0',date:'2026-10-02',title:'Grok, GPT dan perpindahan API otomatis',changes:[{type:'feature',text:'Provider utama dapat dipilih antara Gemini, GPT (OpenAI), dan Grok (xAI), dengan model dan indikator koneksi masing-masing. API key tetap di server.'},{type:'feature',text:'Saat kuota atau batas laju provider habis, aplikasi mencoba provider cadangan yang sudah dikonfigurasi. Hasil menunjukkan provider/model aktual dan riwayat perpindahan; satu aksi tetap satu reservasi batas harian aplikasi.'},{type:'fix',text:'Rangkaian API dibatasi satu deadline 60 detik dan tanpa pengulangan provider. Error key, izin, format, sumber, atau konten tidak memicu perpindahan API.'}]},
 {version:'4.7.5',date:'2026-10-02',title:'Schema Gemini dan verifikasi pratinjau',changes:[{type:'fix',text:'Schema Gemini dipisahkan dari kontrak object strict OpenAI. Field text, draft title/script/angle, dan citations tetap bertipe; validasi hasil serta rujukan tetap wajib sebelum pratinjau.'},{type:'fix',text:'Jalur pratinjau Gemini 3.8 Flash berhasil diuji langsung dari server dengan bahan sintetis. Pemeriksaan sementara sudah dihentikan; model, API key, dan isi konten dipertahankan. HTTP 503 provider tetap ditangani dengan retry dan jeda.'}]},
 {version:'4.7.4',date:'2026-10-02',title:'Pemulihan gangguan Gemini 503',changes:[{type:'fix',text:'Gemini HTTP 503 dicoba ulang maksimal dua kali dengan jeda bertahap pada model yang sama, dalam satu batas waktu 60 detik. Percobaan ulang memakai satu reservasi batas harian aplikasi.'},{type:'fix',text:'Status koneksi dan pratinjau ditampilkan terpisah; pemeriksaan daftar model tidak menghapus informasi kegagalan pratinjau. Kegagalan 503 memberi jeda dan hitung mundur sebelum mencoba model yang sama.'}]},
 {version:'4.7.3',date:'2026-10-02',title:'Perbaikan format JSON Gemini',changes:[{type:'fix',text:'responseFormat.text.mimeType memakai enum APPLICATION_JSON sesuai kontrak REST Gemini. Format kompatibel responseMimeType tetap memakai application/json.'},{type:'fix',text:'Kesalahan struktur payload tidak lagi ditampilkan sebagai model menolak JSON. Tes kontrak memakai snapshot discovery resmi Google.'}]},
 {version:'4.7.2',date:'2026-10-02',title:'Status koneksi AI dan pilihan model',changes:[{type:'feature',text:'Indikator AI membedakan konfigurasi, koneksi API, model tidak tersedia, pratinjau berhasil, dan kegagalan. Cek koneksi mengambil daftar model Gemini yang tersedia; model pratinjau dapat dipilih.'},{type:'fix',text:'HTTP 400 Gemini dibedakan antara key invalid, format JSON, dan model tidak mendukung. Endpoint yang belum mengenali responseFormat mencoba format JSON kompatibel satu kali pada model yang sama.'}]},
 {version:'4.7.1',date:'2026-10-02',title:'Dukungan AI Gemini',changes:[{type:'feature',text:'AI_PROVIDER dapat memakai gemini atau openai. Gemini menggunakan GEMINI_API_KEY dan GEMINI_MODEL; semua bantuan AI tetap melalui pratinjau sebelum diterapkan.'},{type:'fix',text:'Status AI dan panduan variabel mengikuti provider yang dipilih. Respons Gemini terpotong, ditolak, kuota habis, dan model/key tidak valid ditangani tanpa mengubah script.'}]},
 {version:'4.7.0',date:'2026-10-02',title:'Radar Konten dan bantuan AI',changes:[{type:'feature',text:'Radar Hot Issue, Pantauan Channel, dan Referensi memakai tiga lensa editorial, topik custom, berita/RSS, dan link manual. Topik dan sumber disimpan secara eksplisit.'},{type:'feature',text:'Detail isu menampilkan link sumber, penerbit/platform, tanggal publikasi dan peristiwa, verifikasi manual, penanda repost, serta penggabungan isu. Draft Long/Short membawa sumber ke Riset & Aset.'},{type:'feature',text:'Pantauan channel membaca maksimum 10 video publik terbaru dan merekam snapshot views, likes, serta komentar. Perubahan dihitung sejak snapshot yang tersedia.'},{type:'feature',text:'Bantuan AI opsional menyediakan ringkasan/angle, perbaikan script, 3 Short, storyboard, dan pengamatan channel dengan pratinjau. Membutuhkan OPENAI_API_KEY dan OPENAI_MODEL; tidak aktif tanpa konfigurasi.'},{type:'fix',text:'Analytics membedakan periode diminta, tanggal data terakhir, waktu laporan/cache, dan hari laporan Pacific Time. Radar ikut penyimpanan serta backup konten.'}]},
 {version:'4.6.4',date:'2026-10-02',title:'Script ringkas dan progres produksi',changes:[{type:'feature',text:'Tab Script memakai satu editor tanpa kolom Hook dan CTA, dengan Salin Script, jumlah kata/karakter, serta estimasi durasi narasi.'},{type:'feature',text:'Progress bar berdasarkan empat checklist tampil pada detail konten, kartu Kanban, dashboard, dan Semua Konten. Checklist pada detail dapat dibuka dari Progres produksi.'},{type:'fix',text:'Isi dan format Hook/CTA lama tetap dipertahankan saat menyimpan script; tampilan baru tidak menghapus data lama.'}]},
 {version:'4.6.3',date:'2026-10-02',title:'Label kategori video pada konten',changes:[{type:'fix',text:'Badge Long ungu dan Short biru tampil jelas pada kalender, Kanban, dan Semua Konten. Kategori dipilih di editor konten.'},{type:'fix',text:'Kategori video dan filter Long/Short dihapus dari tampilan Note; kategori custom Note tetap tersedia.'},{type:'fix',text:'Kartu Kanban tidak lagi mengulang status proses produksi yang sudah terlihat pada kolom.'},{type:'feature',text:'Kategori video upload tanpa konten dapat dipilih saat upload atau melalui kalender dengan tombol Simpan. Upload lama tanpa kategori ditandai Belum dipilih.'}]},
 {version:'4.6.2',date:'2026-10-02',title:'Kategori video Long dan Short',changes:[{type:'feature',text:'Note mempunyai pilihan kategori video Long atau Short, badge pada kartu, serta filter Long, Short, dan Belum dipilih. Pilihan disimpan lewat tombol Simpan; catatan lama tetap tanpa pilihan.'},{type:'feature',text:'Label Long dan Short dibuat konsisten pada konten, Kanban, dan filter format.'}]},
 {version:'4.6.1',date:'2026-10-02',title:'Data & Backup stabil dan Riwayat Update',changes:[
  {type:'fix',text:'Halaman Data & Backup tetap terbuka saat sinkronisasi; tombol, pesan hasil, dan posisi scroll dipertahankan.'},
  {type:'fix',text:'Kegagalan pemeriksaan Analytics ditampilkan terpisah dan tidak menghilangkan daftar backup.'},
  {type:'fix',text:'Backup manual dilindungi dari permintaan bersamaan; hasil unduhan dan masalah salinan volume ditampilkan dengan jelas.'},
  {type:'feature',text:'Menu Riwayat Update menampilkan versi, tanggal rilis, fitur baru, dan perbaikan aplikasi.'}]},
 {version:'4.6.0',date:'2026-10-02',title:'Format teks dan deteksi link',changes:[{type:'feature',text:'Editor Note, brief, hook, naskah, CTA, dan rencana produksi mendukung bold, italic, underline, ukuran huruf, huruf BESAR/kecil, daftar, dan link.'},{type:'feature',text:'Format ikut tersimpan dalam draft, duplikasi, dan riwayat konten. Note tetap memakai tombol Simpan.'}]},
 {version:'4.5.0',date:'2026-10-02',title:'PostgreSQL, backup, dan statistik harian',changes:[{type:'feature',text:'Migrasi PostgreSQL dengan verifikasi data serta backup harian, manual, dan unduhan.'},{type:'feature',text:'Statistik harian subscriber, views, jam tonton, snapshot total channel, dan ekspor CSV.'}]},
 {version:'4.4.1',date:'2026-10-01',title:'Antrean upload lebih aman',changes:[{type:'fix',text:'Worker berhenti sementara saat kuota API habis dan mempertahankan offset upload serta jadwal native YouTube.'}]},
 {version:'4.4.0',date:'2026-10-01',title:'Analytics channel dan per video',changes:[{type:'feature',text:'Tab Overview, Reach, Engagement, Audience, pendapatan, katalog video, CSV, dan pengelolaan video.'},{type:'fix',text:'Judul video dan data yang sudah tersedia dipertahankan ketika kuota Google habis.'}]},
 {version:'4.3.2',date:'2026-10-01',title:'Simpan secara eksplisit',changes:[{type:'fix',text:'Note disimpan lewat tombol Simpan, kategori dibuat secara eksplisit, dan formulir kosong ditolak.'}]},
 {version:'4.3.1',date:'2026-10-01',title:'Kategori Note',changes:[{type:'feature',text:'Nama menu Note, kategori custom, serta filter catatan berdasarkan kategori.'}]},
 {version:'4.3.0',date:'2026-10-01',title:'Note dan kolom Kanban custom',changes:[{type:'feature',text:'Catatan, tag, pin, arsip, kolom Kanban yang dapat diatur, dan Analytics per video.'}]},
 {version:'4.2.1',date:'2026-10-01',title:'Pembeda status',changes:[{type:'feature',text:'Badge ikon, warna, dan tulisan membedakan tahap produksi dengan status publikasi.'}]},
 {version:'4.2.0',date:'2026-10-01',title:'Tampilan modern dan mobile',changes:[{type:'feature',text:'Sidebar desktop, menu ponsel, editor responsif, dan papan Kanban bergaya Trello.'}]},
 {version:'4.1.0',date:'2026-10-01',title:'Integrasi YouTube Analytics',changes:[{type:'feature',text:'Dashboard Analytics dan izin Google tambahan untuk membaca performa channel.'}]},
 {version:'4.0.0',date:'2026-10-01',title:'Content Hub',changes:[{type:'feature',text:'Dashboard, kalender, Kanban, penyimpanan naskah, riset, pilar, dan riwayat versi konten sebelum produksi.'}]}
];
